### ISSUE TITLE
Funktionale Anforderungen

### ISSUE THREAD

**Issue by Egomann88** [Egomann88/M335_Projektarbeit-Schnitzeljagd#13]
- [x] haptisches Zeichen wenn Aufgabe abgeschlossen
- [x] [Geolocation](https://github.com/Egomann88/TEST_M335_Project/issues/2 )
- [x] [Laufen](https://github.com/Egomann88/TEST_M335_Project/issues/3 )
- [x] [Kamera QR-Code](https://github.com/Egomann88/TEST_M335_Project/issues/4 )
- [x] [Sensor](https://github.com/Egomann88/TEST_M335_Project/issues/5 )
- [x] [Device Status](https://github.com/Egomann88/TEST_M335_Project/issues/6 )
- [x] [WLAN](https://github.com/Egomann88/TEST_M335_Project/issues/7 )
- [x] [Homepage](https://github.com/Egomann88/TEST_M335_Project/issues/8 )
- [x] [Schnitzeljagd Abschluss / Details Page](https://github.com/Egomann88/TEST_M335_Project/issues/9 )
- [x] [Zeitkomponente bei Aufgaben](https://github.com/Egomann88/TEST_M335_Project/issues/10 )
- [x] [Einstellungen und Statistiken](https://github.com/Egomann88/TEST_M335_Project/issues/11 )
- [x] [Alert: Berechtigungen nicht da](https://github.com/Egomann88/TEST_M335_Project/issues/12 )
- [x] [Alert: Details von Aufgaben](https://github.com/Egomann88/TEST_M335_Project/issues/14 )
